# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\Eric6Save\PLForecastingUI\forecasting.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Forecasting(object):
    def setupUi(self, Dialog_Forecasting):
        Dialog_Forecasting.setObjectName("Dialog_Forecasting")
        Dialog_Forecasting.resize(600, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("forecast.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Forecasting.setWindowIcon(icon)
        Dialog_Forecasting.setSizeGripEnabled(True)
        self.label_Title = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_Title.setGeometry(QtCore.QRect(175, 30, 261, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.label_Forecasting = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_Forecasting.setGeometry(QtCore.QRect(50, 160, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_Forecasting.setFont(font)
        self.label_Forecasting.setObjectName("label_Forecasting")
        self.Button_close = QtWidgets.QPushButton(Dialog_Forecasting)
        self.Button_close.setGeometry(QtCore.QRect(470, 450, 100, 30))
        self.Button_close.setObjectName("Button_close")
        self.label_Paramter = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_Paramter.setGeometry(QtCore.QRect(50, 400, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_Paramter.setFont(font)
        self.label_Paramter.setObjectName("label_Paramter")
        self.lineEdit_ProjectName = QtWidgets.QLineEdit(Dialog_Forecasting)
        self.lineEdit_ProjectName.setGeometry(QtCore.QRect(200, 100, 300, 31))
        self.lineEdit_ProjectName.setObjectName("lineEdit_ProjectName")
        self.dateTimeEdit_End = QtWidgets.QDateTimeEdit(Dialog_Forecasting)
        self.dateTimeEdit_End.setGeometry(QtCore.QRect(380, 350, 130, 20))
        self.dateTimeEdit_End.setFrame(False)
        self.dateTimeEdit_End.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_End.setDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_End.setDate(QtCore.QDate(2007, 1, 1))
        self.dateTimeEdit_End.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_End.setMaximumDate(QtCore.QDate(2007, 12, 31))
        self.dateTimeEdit_End.setMinimumDate(QtCore.QDate(2007, 1, 1))
        self.dateTimeEdit_End.setObjectName("dateTimeEdit_End")
        self.dateTimeEdit_Start = QtWidgets.QDateTimeEdit(Dialog_Forecasting)
        self.dateTimeEdit_Start.setGeometry(QtCore.QRect(200, 350, 130, 20))
        self.dateTimeEdit_Start.setFrame(False)
        self.dateTimeEdit_Start.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_Start.setDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_Start.setDate(QtCore.QDate(2007, 1, 1))
        self.dateTimeEdit_Start.setTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit_Start.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_Start.setMaximumDate(QtCore.QDate(2007, 12, 31))
        self.dateTimeEdit_Start.setMinimumDate(QtCore.QDate(2007, 1, 1))
        self.dateTimeEdit_Start.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.dateTimeEdit_Start.setObjectName("dateTimeEdit_Start")
        self.comboBox_dateset = QtWidgets.QComboBox(Dialog_Forecasting)
        self.comboBox_dateset.setGeometry(QtCore.QRect(280, 220, 150, 30))
        self.comboBox_dateset.setObjectName("comboBox_dateset")
        self.comboBox_dateset.addItem("")
        self.comboBox_dateset.addItem("")
        self.comboBox_dateset.addItem("")
        self.comboBox_dateset.addItem("")
        self.Button_ok = QtWidgets.QPushButton(Dialog_Forecasting)
        self.Button_ok.setGeometry(QtCore.QRect(350, 450, 100, 30))
        self.Button_ok.setObjectName("Button_ok")
        self.comboBox_Forecasting = QtWidgets.QComboBox(Dialog_Forecasting)
        self.comboBox_Forecasting.setGeometry(QtCore.QRect(280, 160, 150, 30))
        self.comboBox_Forecasting.setObjectName("comboBox_Forecasting")
        self.comboBox_Forecasting.addItem("")
        self.comboBox_Forecasting.addItem("")
        self.comboBox_Forecasting.addItem("")
        self.label_DataSource = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_DataSource.setGeometry(QtCore.QRect(50, 220, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_DataSource.setFont(font)
        self.label_DataSource.setObjectName("label_DataSource")
        self.checkBox_Season = QtWidgets.QCheckBox(Dialog_Forecasting)
        self.checkBox_Season.setGeometry(QtCore.QRect(240, 405, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.checkBox_Season.setFont(font)
        self.checkBox_Season.setObjectName("checkBox_Season")
        self.checkBox_Holiday = QtWidgets.QCheckBox(Dialog_Forecasting)
        self.checkBox_Holiday.setGeometry(QtCore.QRect(410, 405, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.checkBox_Holiday.setFont(font)
        self.checkBox_Holiday.setObjectName("checkBox_Holiday")
        self.label_ProjectName = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_ProjectName.setGeometry(QtCore.QRect(50, 100, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_ProjectName.setFont(font)
        self.label_ProjectName.setObjectName("label_ProjectName")
        self.label_TimeRange = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_TimeRange.setGeometry(QtCore.QRect(50, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_TimeRange.setFont(font)
        self.label_TimeRange.setObjectName("label_TimeRange")
        self.label_ForecastType = QtWidgets.QLabel(Dialog_Forecasting)
        self.label_ForecastType.setGeometry(QtCore.QRect(50, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_ForecastType.setFont(font)
        self.label_ForecastType.setObjectName("label_ForecastType")
        self.radioButton_single = QtWidgets.QRadioButton(Dialog_Forecasting)
        self.radioButton_single.setGeometry(QtCore.QRect(220, 290, 115, 19))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.radioButton_single.setFont(font)
        self.radioButton_single.setChecked(False)
        self.radioButton_single.setObjectName("radioButton_single")
        self.radioButton_range = QtWidgets.QRadioButton(Dialog_Forecasting)
        self.radioButton_range.setGeometry(QtCore.QRect(400, 290, 115, 19))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.radioButton_range.setFont(font)
        self.radioButton_range.setChecked(True)
        self.radioButton_range.setObjectName("radioButton_range")

        self.retranslateUi(Dialog_Forecasting)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Forecasting)

    def retranslateUi(self, Dialog_Forecasting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Forecasting.setWindowTitle(_translate("Dialog_Forecasting", "负荷预测"))
        self.label_Title.setText(_translate("Dialog_Forecasting", "未来负荷预测"))
        self.label_Forecasting.setText(_translate("Dialog_Forecasting", "预测算法："))
        self.Button_close.setText(_translate("Dialog_Forecasting", "取消"))
        self.label_Paramter.setText(_translate("Dialog_Forecasting", "参数因子："))
        self.dateTimeEdit_End.setDisplayFormat(_translate("Dialog_Forecasting", "yyyy/M/d"))
        self.dateTimeEdit_Start.setDisplayFormat(_translate("Dialog_Forecasting", "yyyy/M/d"))
        self.comboBox_dateset.setItemText(0, _translate("Dialog_Forecasting", "DataSet"))
        self.comboBox_dateset.setItemText(1, _translate("Dialog_Forecasting", "Dataset2005"))
        self.comboBox_dateset.setItemText(2, _translate("Dialog_Forecasting", "Dataset2006"))
        self.comboBox_dateset.setItemText(3, _translate("Dialog_Forecasting", "Dataset2007"))
        self.Button_ok.setText(_translate("Dialog_Forecasting", "确定"))
        self.comboBox_Forecasting.setItemText(0, _translate("Dialog_Forecasting", "SVM回归分析"))
        self.comboBox_Forecasting.setItemText(1, _translate("Dialog_Forecasting", "均值修正预测"))
        self.comboBox_Forecasting.setItemText(2, _translate("Dialog_Forecasting", "多元线性回归"))
        self.label_DataSource.setText(_translate("Dialog_Forecasting", "数   据   源："))
        self.checkBox_Season.setText(_translate("Dialog_Forecasting", "季节"))
        self.checkBox_Holiday.setText(_translate("Dialog_Forecasting", "节假日"))
        self.label_ProjectName.setText(_translate("Dialog_Forecasting", "项   目   名："))
        self.label_TimeRange.setText(_translate("Dialog_Forecasting", "时间范围："))
        self.label_ForecastType.setText(_translate("Dialog_Forecasting", "预测类型："))
        self.radioButton_single.setText(_translate("Dialog_Forecasting", "单天预测"))
        self.radioButton_range.setText(_translate("Dialog_Forecasting", "范围预测"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Forecasting = QtWidgets.QDialog()
    ui = Ui_Dialog_Forecasting()
    ui.setupUi(Dialog_Forecasting)
    Dialog_Forecasting.show()
    sys.exit(app.exec_())

